# for loop in python


name = "hello world"
for i in name:
    print(i)


name = "thrishanth"
for i in name:
    print(i)
    if i == "i":
        print("this is something special ")

name = "sunnyyyy"
for i in name:
    print(i,end="$")
print ()


colors = ["red", "green", "blue", "yellow"]
for color in colors:
    print(color)
    for i in color:
        print(i)

for i in range(5):
    print(i + 1)

for i in range (1,10,2):
    print(i)

#today i have learnt about for loop in python