print("hello world this is my day2 of learning python\nand i am excited to learn more")

# today i will learn about comments , escape sequences, and print statements

print("hello this is sunnyy") # okk this looks good 

'''
This is a multi-line comment.
'''

print("hello world \"sunny is a bad boy \" \n this is a new line")

print("hello world", "6", "7", sep="$")

print("hello world", "6", "7",)


print("hello world", "6", "7", "8", sep= "$", end =" bye bye\n")
print("sunnyyy")

"""
this is what i have learned today
1. Comments can be single-line or multi-line.
2. Escape sequences like \n for new line and \" for quotes can be used in strings.
3. The print function can take multiple arguments and format output using sep and end parameters.
4. The sep parameter defines the separator between multiple arguments in print.
5. The end parameter defines what to print at the end of the output, allowing customization ofthe output format.
"""