# today i will learn about variables and data types

a = 10 
print(a)
b="sunnyyy:"
print(b)

a=10 
b=123
print(a+b)

a=10 
b= "sunnyyy"
print(a)
print(b)
print("the type of a is ", type(a))
print("the type of b is ", type(b))

a=10 
b= "sunnyyy"
c= True
print(a)
print(b)
print("the type of a is ", type(a))
print("the type of b is ", type(b))
print("the type of c is ", type(c))


a= 10 
b="sunny"
c= True
d= None
print("the type of a is ", type(a))
print("the type of b is ", type(b))
print("the type of c is ", type(c))
print("the type of d is ", type(d))

# Variables can store different data types, including integers, strings, booleans, and None.
# The type() function is used to check the data type of a variable.

'''
this is what i have learned today
1. Variables can hold different data types like integers, strings, booleans, and None'''