# today i am going to learn about opwerators in python and also going to create a simple calculator

print(5+3)  # Addition
print(10-2)  # Subtraction  
print(4*2)  # Multiplication
print(10/3)  # Division
print(10%3)  # Modulus (Remainder)
print(10//3)  # Floor Division (Integer Division)
print(2**3)  # Exponentiation (Power)


a = 10 
b = 5

print ("the value of",a,"+",b,"is",a+b)
print("the value of",a,"-",b,"is",a-b)
print("the value of",a,"*",b,"is",a*b)
print("the value of",a,"/",b,"is",a/b)
print("the value of",a,"%",b,"is",a%b)  
print("the value of",a,"//",b,"is",a//b)
print("the value of",a,"**",b,"is",a**b)



#this is a simple calculator program which i have done today using operators in python also it is my first excerise in python