#STRINGS IN PYTHON


namex = "ilsaa"
friend = "sunyy"

print("hello, " + namex)

sunny  = 'hey thrishanth how are you, \"i think u are doing great\" okk byee'
print(sunny)

name = ''' (heyy how are u doing
is \"everything okkk\"
yeahh i know it will be okkk)'''

print("hello, " + name + sunny )

a="hello"
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

sunnygty = "this to inform u all that tomorrow is an holiday so just practice coding and build ur skills"

for character in sunny:
    print(character)


mama = "hello, world!"
for character in mama:
    print(character)


namesunny = str(input())
for character in namesunny:
    print(character)


